2021-11-28 10:24:44,410 INFO    MainThread:28170 [wandb_setup.py:_flush():71] setting env: {}
2021-11-28 10:24:44,410 INFO    MainThread:28170 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-28 10:24:44,410 INFO    MainThread:28170 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-28 10:24:44,410 INFO    MainThread:28170 [wandb_init.py:_log_setup():371] Logging user logs to /Users/hamzeasadi/python/computationalML/computational-ml/pytorch/wandb/run-20211128_102444-tfzu9pet/logs/debug.log
2021-11-28 10:24:44,410 INFO    MainThread:28170 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/hamzeasadi/python/computationalML/computational-ml/pytorch/wandb/run-20211128_102444-tfzu9pet/logs/debug-internal.log
2021-11-28 10:24:44,411 INFO    MainThread:28170 [wandb_init.py:init():404] calling init triggers
2021-11-28 10:24:44,411 INFO    MainThread:28170 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2021-11-28 10:24:44,411 INFO    MainThread:28170 [wandb_init.py:init():449] starting backend
2021-11-28 10:24:44,411 INFO    MainThread:28170 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2021-11-28 10:24:44,426 INFO    MainThread:28170 [backend.py:ensure_launched():199] starting backend process...
2021-11-28 10:24:44,437 INFO    MainThread:28170 [backend.py:ensure_launched():204] started backend process with pid: 28178
2021-11-28 10:24:44,441 INFO    MainThread:28170 [wandb_init.py:init():458] backend started and connected
2021-11-28 10:24:44,447 INFO    MainThread:28170 [wandb_init.py:init():519] updated telemetry
2021-11-28 10:24:44,470 INFO    MainThread:28170 [wandb_init.py:init():549] communicating current version
2021-11-28 10:24:45,837 INFO    MainThread:28170 [wandb_init.py:init():554] got version response 
2021-11-28 10:24:45,837 INFO    MainThread:28170 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-11-28 10:24:46,044 INFO    MainThread:28170 [wandb_init.py:init():592] starting run threads in backend
2021-11-28 10:24:46,084 INFO    MainThread:28170 [wandb_run.py:_console_start():1816] atexit reg
2021-11-28 10:24:46,084 INFO    MainThread:28170 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.REDIRECT
2021-11-28 10:24:46,085 INFO    MainThread:28170 [wandb_run.py:_redirect():1695] Redirecting console.
2021-11-28 10:24:46,086 INFO    MainThread:28170 [wandb_run.py:_redirect():1751] Redirects installed.
2021-11-28 10:24:46,086 INFO    MainThread:28170 [wandb_init.py:init():619] run started, returning control to user process
2021-11-28 10:24:46,087 INFO    MainThread:28170 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2021-11-28 10:24:46,087 INFO    MainThread:28170 [wandb_run.py:_restore():1758] restore
2021-11-28 10:24:48,101 INFO    MainThread:28170 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 839
  total_bytes: 839
}

2021-11-28 10:24:48,393 INFO    MainThread:28170 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 839
  total_bytes: 839
}

2021-11-28 10:24:49,067 INFO    MainThread:28170 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 839
  total_bytes: 2414
}

2021-11-28 10:24:49,170 INFO    MainThread:28170 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 839
  total_bytes: 2440
}

2021-11-28 10:24:49,282 INFO    MainThread:28170 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 839
  total_bytes: 2440
}

2021-11-28 10:24:49,387 INFO    MainThread:28170 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2440
  total_bytes: 2440
}

2021-11-28 10:24:49,491 INFO    MainThread:28170 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2440
  total_bytes: 2440
}

2021-11-28 10:24:49,594 INFO    MainThread:28170 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2440
  total_bytes: 2440
}

2021-11-28 10:24:49,697 INFO    MainThread:28170 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2440
  total_bytes: 2440
}

2021-11-28 10:24:49,801 INFO    MainThread:28170 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2440
  total_bytes: 2440
}

2021-11-28 10:24:49,908 INFO    MainThread:28170 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2440
  total_bytes: 2440
}

2021-11-28 10:24:50,295 INFO    MainThread:28170 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2440
  total_bytes: 2440
}

2021-11-28 10:24:50,789 INFO    MainThread:28170 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2440
  total_bytes: 2440
}
local_info {
}

2021-11-28 10:24:51,938 INFO    MainThread:28170 [wandb_run.py:_append_files():2184] logging synced files
